name: "Sync to Google Drive"
description: "Syncs repo files to Google Drive folders"
inputs:
  credentials:
    description: "Base64-encoded Google Service Account JSON"
    required: true
  github_token:
    description: "GitHub token for API calls (e.g., creating PRs)"
    required: true
    default: ${{ github.token }}
  trigger_event_name:
    description: "The event name that triggered the workflow (e.g., push, schedule)"
    required: true
runs:
  using: "node20"
  main: "dist/sync_to_drive.js"
  pre: "setup.js"
