name: sync_to_drive

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install_deps
        run: npm install

      - name: run_sync
        uses: ./
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
